services:
  db:
    image: postgres:16.3-alpine
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
